# -*- coding: utf-8 -*-
"""Counting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1okjGUedJ9Pe8uJ5_5013g_s71DkNP5t_
"""

scores = input().split()
fail = 0

for i in range(0, len(scores)):
  if (int(scores[i]) < 60):
    fail += 1

print("不及格的數量為：{}".format(fail))


total = 0
for i in range(len(scores)):
    total+=int(scores[i])

print(f"平均為{total/len(scores)}")
